// Generated by CoffeeScript 1.12.2
(function() {
  var channel, mongoose;

  mongoose = require('mongoose');

  channel = new mongoose.Schema({
    name: String,
    messages: [
      {
        userId: String,
        time: Number,
        message: String
      }
    ]
  });

  module.exports = channel;

}).call(this);
